export const OPEN_CHAT = "OPEN_CHAT"
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE"
export const CHAT_PAUSE = "CHAT_PAUSE"
export const CHAT_ONLINE = "CHAT_ONLINE"
export const NEW_MESSAGE = "NEW_MESSAGE"
export const CHAT_CONNECT = "CHAT_CONNECT"
export const CHAT_LEAVE = "CHAT_LEAVE"
export const CHAT_CLEAR = "CHAT_CLEAR"
