export const CHECK_FORM = 'CHECK_FORM'

export const ADD_USER = 'ADD_USER';

export const GET_EXAMPLE_FORM = 'GET_EXAMPLE_FORM'

export const USER_OR_FORM_NOTFOUND = 'USER_OR_FORM_NOTFOUND'

export const CREATE_URL_FORM = 'CREATE_URL_FORM';

export const CLEAR_CHECKFORM_STATE = 'CLEAR_CHECKFORM_STATE';

export const SET_CONTACTS = "SET_CONTACTS";
