export const CHECK_FORM_UUID = 'CHECK_FORM_UUID';
export const SEND_FILLING_FORM = 'SEND_FILLING_FORM'
export const ERR_INTERNAL = "ERR_INTERNAL";
export const SEND_FILLING_FORM_ERROR = "SEND_FILLING_FORM_ERROR"

export const FORM_DELIVERED = "FORM_DELIVERED";

export const CLEAR_SENTFORM = "CLEAR_SENTFORM";
